#AUTOEXEC.BAT
#Copyright (C) 2022 Floatingdream All Rights Reserved.
color 1E
echo                     _____  __                                          
echo                    / ___/ / /               __   _                    
echo                   / /__  / / ____   ____   / /_ (_)____   ___    
echo                  /  __/ / / / __ \ / __ \ / __// // __ \ / __ \ 
echo                 / /    / / / /_/ // /_/ // /_ / // / / // /_/ /
echo                /_/    /_/  \____/ \___\_\\__//_//_/ /_/ \__  / 
echo                                                      __   / /
echo                                                      \ \_/ /
echo                                                       \___/ 
echo                       __
echo                      / /
echo                 ____/ / _____ ___   ____    ______
echo                / __  / / ___// _ \ / __ \  / _  _ \
echo               / /_/ / / /   /  __// /_/ / / // // / NDC
echo               \____/ /_/    \___/ \___\_\/_//_//_/ Kernel
echo                                 3.3
echo             Copyright (C) 2022 Floatingdream All Rights Reserved.
#Boot Program
about
